### ISSUE TITLE
Скачать исходники книги с lesswrong.com

### ISSUE THREAD

**Issue by worldmind** [worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book#1]
Книга тут https://www.lesswrong.com/rationality

Спрашивал у них в саппорте, сказали что у них даже веб-морда есть -  lesswrong.com/graphiql и дали пару запросов (хотя второй похоже не работает, не возвращает markdown, хотя может и не надо, вероятно html будет проще парсить):
```
{
  collections(input: {terms: {view: "collectionsBySlug", slug: "rationality", limit: 10}}) {
    results {
      _id
      title
      books {
        title
        sequences {
          title
          chapters {
            title
            posts {
              title
              user {
                displayName
              }
              contents {
                html
              }
            }
          }
        }
      }
    }
  }
}
```
и
```
{
  collection(input: {selector: {slug: "rationality"}}) {
    result {
      _id
      title
      books {
        title
        sequences {
          title
          chapters {
            title
            posts {
              title
              user {
                displayName
              }
              contents {
                markdown
              }
            }
          }
        }
      }
    }
  }
}
```
нужно покрутить эти запросы, желательно получать тэги, надо проверить что авторы есть

надо сделать скрипт на Python (положить например в scripts), который скачает все эссе и разложит по файлам в дерево папок вида `lesswrong.com/имя_тома/буква_цепочки_имя_цепочки/порядковый_номер_эссе_в_цепочке_название_эссе` вместе с тэгами, авторами и т.п которые в отдельные файлы стоит положить, взять то же имя и добавить `.meta`.

**Comment by worldmind** [comment]
@alexdrupal ты же ковырял немного эти запросы, поделись тем что нашёл

**Comment by yozhio** [comment]
https://www.lesswrong.com/graphiql

1) Получить список книг в библиотеке и выбрать параметр slug для идентификации нужной книги:

{
  collections(input: {enableTotal: true}) {
    results {
      title
      slug
    }
  }
}

Или взять с сайта часть пути до книги
https://www.lesswrong.com/{slug}

2) Получить структуру книги:

{
  collection(input: {selector: {slug: "rationality"}}) {
    result {
      title
      version
      books {
        title
        sequences {
          title
          contents {
            editedAt
            html
          }
          chapters {
            posts {
              _id
            }
          }
        }
      }
    }
  }
}

3) Выбрать из структуры все posts._id и выкачать главы по одной:

{
  post(input: {selector: {_id: "uXn3LyA8eNqpvdoZw"}}) {
    result {
      _id
      title
      user {
        displayName
      }
      modifiedAt
      pageUrl
      contents {
        html
      }
      tags {
        name
      }
    }
  }
}

**Comment by worldmind** [comment]
При наличии готовых запросов нет смысла использовать специальные библиотеки для graphql, просто слать их библиотекой [requests](https://requests.readthedocs.io/en/latest/) и получать json ответ

**Comment by worldmind** [comment]
А для сохраненипя файлов [pathlib](https://realpython.com/python-pathlib/)

**Comment by yozhio** [comment]
По вопросу авторства для post. Проверила поля
```
      organizers {
        displayName
      }
      author
      coauthors {
        displayName
      }
      user {
        displayName
      }
      reviewedByUser {
        displayName
      }
```
organizers, coauthors - пустые
author совпадает с user или не заполнено
reviewedByUser заполнено, но по названию это автор ревью?

Статистика по posts (count | author | user | reviewedByUser):
```
     89  "author": "Eliezer Yudkowsky",  "user": "Eliezer Yudkowsky",  "reviewedByUser": "habryka" 
    215  "author": "Eliezer_Yudkowsky",  "user": "Eliezer Yudkowsky",  "reviewedByUser": "habryka" 
      8  "author": "Eliezer Yudkowsky",  "user": "Eliezer Yudkowsky",  "reviewedByUser": "mingyuan" 
      7  "author": "Eliezer_Yudkowsky",  "user": "Eliezer Yudkowsky",  "reviewedByUser": "mingyuan" 
      2  "author": "Eliezer_Yudkowsky",  "user": "Eliezer Yudkowsky",  "reviewedByUser": "Raemon" 
     10  "author": null,  "user": "Eliezer Yudkowsky",  "reviewedByUser": "habryka" 
      5  "author": "Rob Bensinger",  "user": "Rob Bensinger",  "reviewedByUser": "habryka" 
      1  "author": "Rob Bensinger",  "user": "Rob Bensinger",  "reviewedByUser": "mingyuan" 
```
Автор здесь получается user; и плюс некий ревьюер - либо один, либо только последний.

**Comment by worldmind** [comment]
Давай все эти поля созраним в meta, на всякий случай

**Comment by worldmind** [comment]
https://www.lesswrong.com/rationality
прямо под заголовком "Map and Territory" есть текст

> What is a belief, and what makes some beliefs work better than others? These four sequences explain the Bayesian notions of rationality, belief, and evidence. A running theme: the things we call “explanations” or “theories” may not always function like maps for navigating the world. As a result, we risk mixing up our mental maps with the other objects in our toolbox.

можешь глянуть есть ли он в ответете graphql?

**Comment by yozhio** [comment]
```
{
  collection(input: {selector: {slug: "rationality"}}) {
    result {
      title
      createdAt
      contents {
        html
      }
      user {
        displayName
      }
      version
      books {
        title
        contents{
          html
        }
        createdAt
        sequences {
          _id
          title
          user {
            displayName
          }
          contents {
            editedAt
            html
          }
          chapters {
            posts {
              title
              _id
            }
          }
        }
      }
    }
  }
}
```
Для collection (RATIONALITY: A-Z) есть:
```
      createdAt
      contents {
        html
      }
      user {
        displayName
      }
```
Для book (Map and Territory) есть:
```
        contents{
          html
        }
        createdAt
```
Может положить файлы в одноименные директории в том же стиле: content.html, metadata? И для sequence тогда тоже исключение в виде отдельной главы можно убрать.

**Comment by worldmind** [comment]
Да, давай

**Comment by yozhio** [comment]
Что-то нужно еще по этой задаче добавить?

**Comment by worldmind** [comment]
Надёюсь всё, если что всплывёт, то это уже отдельная история.
Благодарю, можно начинать следующий.
