### ISSUE TITLE
Написать мануал для переводчиков

### ISSUE THREAD

**Issue by worldmind** [worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book#11]
Надо будет обсудить, основная задача дать неайтишным людям ясные шаги для того чтобы они могли прямо в браузере, без установки/настройки софта:
1. Создать ветку для перевода одного эссе (имя ветки - имя эссе плюс ник перводчика)
2. Редактировать докбук файл эссе (которые в book.ru) в браузерном редакторе делая промежуточные коммиты если  не за один заход всё делается, что скорее всего
3. Создать Pull Request и отправить его на ревью
4. Вносить правки по результатам ревью

**Comment by worldmind** [comment]
Надо будет дописать что надо мне написать чтобы я добавмл пользователя в участники

**Comment by worldmind** [comment]
или копировать путь к файлу и из него создавать ветку проще будет

**Comment by worldmind** [comment]
И при создани ветки надо написать что создавать от main, легко не заметить и ответвится от предыдущей ветки

**Comment by worldmind** [comment]
И про то как делать ревью ибо пееводчик может ревьювить других

**Comment by worldmind** [comment]
> Пример переноса перевода на github/docbook:
> https://github.com/worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book/pull/18
> Там есть вкладка "Files changed" где нажав шестерёнку можно выбрать split view и увидеть все изменения по отношению к англоязчному исходнику:
> https://github.com/worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book/pull/18/files?diff=split&w=0
> при наведении мышки на параграф появляется кнопка "+" для добавления комментариев если таковые есть для конкретного параграфа, а кнопка "Review changes" позволяет одобрить или нет весь перевод.
> Я исхожу из того, что это весьма удобный инструмент совместной работы, хотя для создания таких запросов на внесение переводов надо чуть поразбираться, но ревью выглядит проще простого.

написал это в чат переводчиков

**Comment by worldmind** [comment]
Внёс несколько правок https://github.com/worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book/pull/21 запросил ревью
Можешь по последнему моему коменту выше дополнить мануал?

**Comment by yozhio** [comment]
Добавила
