### ISSUE TITLE
Конвертировать скачанную книгу в формат DocBook и настроить сборку PDF и chunked HTML

### ISSUE THREAD

**Issue by worldmind** [worldmind/Rationality-From_AI_To_Zombies_by_Eliezer_Yudkowsky.book#2]
Нужен скрипт на Python, который конвертирует скачанные в #1 исходники в формат DocBook 5.x (лучше 5.2, но в убунте в `/usr/share/xml/docbook/schema/xsd/` вижу только 5.0) положив каждый том в отдельный файл в папке `book.english` и убедится что из них собираются корректные HTML и PDF.
Пример docbook книги и инструментов для сборки есть [тут](https://github.com/worldmind/ratiocracy.book) (см. Makefile для сборки), **но есть нюансы**:
1. Там у меня кастомная сборка PDF, так (скорее всего) делать не надо, это legacy связанное с тем, что изначально делал в LaTeX, надо смотреть официальные способы генерации PDF, а это видимо xsl-fo, см. [тут](https://help.ubuntu.com/community/DocBook ) и [тут](https://stackoverflow.com/questions/2615002/how-to-generate-pdf-from-docbook-5-0). Плюс там есть нюанс с кириллицей - нужны шрифты, натыкался на [такой](https://github.com/eduardtibet/foponts) проект, но надо смотреть, скорее всего лучше найти пакеты с этими шрифтами в убунте или самим их скачивать.
2. Некоторые элементы мне там не потребовались, надо будет на них посмотреть отдельно, например, [таблицы](https://tdg.docbook.org/tdg/5.2/cals.informaltable) (есть ещё [cals.table](https://tdg.docbook.org/tdg/5.2/cals.table) и [html версии](http://www.sagehill.net/docbookxsl/Tables.html) обоих вариантов, но CALS выглядит получше) и [рисунки](https://stackoverflow.com/questions/9177130/docbook-more-images-in-one-figure) (там немного другой вопрос, но пример понятен), хотя с ними проблем не должно быть, в основном вопрос по формулам, я надеюсь что нам хватит [equation](https://tdg.docbook.org/tdg/5.2/equation.html) и [inlineequation](https://tdg.docbook.org/tdg/5.2/inlineequation), но если попадётся что-то слишком сложное придётся смотреть [MathML](http://www.sagehill.net/docbookxsl/MathML.html), но это не часть стандарта DocBook, для него нужны дополнительные пакеты, видимо `docbook-mathml`.
3. Надо разобраться с [генерацией html из нескольких томов](http://www.sagehill.net/docbookxsl/Olinking.html#d0e41064), плюс со ссылками между томами, скорее всего они будут, томам нужно указать [volumenum](https://tdg.docbook.org/tdg/5.2/volumenum) и [seriesvolnums](https://tdg.docbook.org/tdg/5.0/seriesvolnums) и как понимаю это позволит указывать ссылки с targetdoc/targetptr но не пробовал, [тут](http://www.sagehill.net/docbookxsl/Olinking.html#Db5UnivOlinking) есть что-то.

**Comment by worldmind** [comment]
Думаю лучше всего начать с создания руками мелкого, но двухтомного docbook проекта с нужными тэгами и отладить на нём инфраструктуру сборки pdf/html, проверить как все тэги работают, а потом уже приступать к конвертации.

**Comment by worldmind** [comment]
https://book.huihoo.com/docbook-xsl-the-complete-guide/Profiling.html

**Comment by worldmind** [comment]
Смотрю картинок не так и много, можно наверное и их положить в репозиторий - скачивать когда книга скачивается, а не собирается докбук

**Comment by worldmind** [comment]
Расширений файлов лучше какое-то докбук специфичное сделать - dbk или docbook

**Comment by worldmind** [comment]
Установку docbook-xsl fop надо добавить в Makefile

**Comment by worldmind** [comment]
В `lesswrong.com/Rationality\:\ A-Z//01_Map_and_Territory/03_Noticing_Confusion/11_Illusion_of_Transparency\:__Why_No_One_Understands_You/content.book`
```
listeners would perceive the meaning presented as “standard.”<superscript>6</superscript>
```
а потом ниже
```
<para><superscript>6</superscript> Other idioms tested included “come the uncle over someone,” “to go by the board,” and “to lay out in lavender.” Ah, English, such a lovely language.</para>
```

надо  это конвертировать в [footnote](https://tdg.docbook.org/tdg/5.2/footnote) иначе оно неправильно в pdf размещается, может уехать на другую страницу.

**Comment by worldmind** [comment]
> Смотрю картинок не так и много, можно наверное и их положить в репозиторий - скачивать когда книга скачивается, а не собирается докбук

Причём растровые можно пожать чуток, смотрю тут https://www.lesswrong.com/posts/eDpPnT7wdBwWPGvo5/2-place-and-1-place-words картинка маленькая, а в пдф она намного больше, можно место съэкономить уменьшив её

**Comment by worldmind** [comment]
Я думаю в конечном итоге надо будет докбук положить в отдельную папку, во-первых, чтобы не смешивать скачанные исходники и сгенерированные файлы, а во-вторых, для докбука можно сделать облегчённую структуру - там не надо папок с именем эссе и content файлами, сразу докбук файл с именем эссе.

**Comment by worldmind** [comment]
То что в квадратных скобках это ссылки на литературу - [bibliography](https://tdg.docbook.org/tdg/sdocbook/5.2/bibliography), у меня есть пример [определения](
https://github.com/worldmind/ratiocracy.book/blob/main/ratiocracy.docbook#L18061) и [использования](https://github.com/worldmind/ratiocracy.book/blob/main/ratiocracy.docbook#L8240), но в данном случае
1. у нас неструктурированные данные, поэтому придётся использовать [bibliomixed](https://tdg.docbook.org/tdg/sdocbook/5.2/bibliomixed)
2. нет смысла выносить всю библиографию отдельно как у меня, корректнее будет в каждом эссе её описывать

**Comment by yozhio** [comment]
Не доделано
1) при загрузке html (download_from_lesswrong.com.py) работать с параметрами  через объект
2) разобраться с валидацией docbook файла - есть варнинги об аттрибуте status в ряде элементов
3) при генерации pdf остались варнинги: есть блоки с выходом текста за пределы страницы, 2-3 символа не попадают в шрифты
4) в докбуке прописать в картинки размеры для pdf, как для html
5) для картинок перетащить в докбук выравнивание и обтекание если есть

**Comment by worldmind** [comment]
Основное это 2, об оформлении пока не нужно особо волноваться, надо в первую очередь функционал, нам ещё придётся корректировать докбук для генерации html

**Comment by worldmind** [comment]
ну и все докбук файлы нужно перенести в `book.english` и упростить структуру - там не нужны папки с именем эссе и файлом content.dbk, достаточно файла с именем эссе

**Comment by worldmind** [comment]
Нам нужно не смешивать скачанные исходники и сгенерённые данные, в какой-то момент про исходники можно будет забыть, они не долны мешаться под руками когда будет работа над переводом.

**Comment by worldmind** [comment]
Вроде тут всё?

**Comment by yozhio** [comment]
**Варнинги в логе при генерации pdf-файлов**
1) При составлении fo файла не используются оригинальные параметры картинок.
Например в файле 04_Fake_Causality.dbk
```
<mediaobject>
    <imageobject role="html">
      <imagedata contentwidth="69.03%" fileref="./img/726b977654b9a6db1d77eecc20169b5e.png" format="PNG" scalefit="1"/>
    </imageobject>
    <imageobject role="fo">
      <imagedata contentdepth="100%" fileref="./img/726b977654b9a6db1d77eecc20169b5e.png" format="PNG" scalefit="1" width="100%"/>
    </imageobject>
  </mediaobject>
```
для профиля html есть размер картинки, а для fo он всегда берется по максимуму.

Как вариант, можно при составлении dbk попытаться исправить параметры для роли fo, или создать новую роль fo_img с нужными параметрами. Тогда переключить на новую роль при конвертации можно через параметр preferred.mediaobject.role (https://www.sagehill.net/docbookxsl/GraphicSelection.html#SelectByRole). Просто переключать на роль html в текущем виде не надо, там для отдельных картинок параметры составлены так, что в pdf их растягивает за пределы страницы.

2) The Machine in the Ghost
- Нумерация пунктов с 10 по 37 включительно залазит на текст абзаца. Вероятно, надо посмотреть разметку в dbk.
В логе
```[WARN] FOUserAgent - The contents of fo:block line 1 exceed the available area in the inline-progression direction by 4030 millipoints. (See position 1878:216)```
В тексте книги
```10.A verbal definition works well enough in practice to point out the intended cluster of similar```

-  Блок выходит за пределы страницы. Вероятно, надо посмотреть разметку в dbk.
В логе
```[WARN] FOUserAgent - The contents of fo:inline line 1 exceed the available area in the inline-progression direction by more than 50 points. (See position 1948:401)```
В тексте книги
```￼[Editor’s Note: This is an abridgement of the original version of this essay```

- Символы которые fop не может найти в шрифтах
```[WARN] FOUserAgent - Glyph "￼" (0xfffc) not available in font "CourierPrime-Regular".```
```[WARN] FOUserAgent - Glyph "?" (0xdbff) not available in font "CharisSIL".```
```[WARN] FOUserAgent - Glyph "?" (0xdc06) not available in font "CharisSIL".```

3) Mere Reality
- Не влазят в один блок картинка и текст. Вероятно, надо посмотреть разметку в dbk.

В логе
```[WARN] FOUserAgent - The contents of fo:block line 1 exceed the available area in the inline-progression direction by 8960 millipoints. (See position 520:98)```

В тексте книги
```the dawn days of science fiction, alien invaders would occasionally kidnap a girl in a torn dress and carry her off for intended ravishing, as lovingly depicted on many ancient maga- zine covers. Oddly enough, the aliens never go after men in torn shirts.```

- Не влазят в один блок картинка и текст. Вероятно, надо посмотреть разметку в dbk.

В логе
```[WARN] FOUserAgent - The contents of fo:block line 1 exceed the available area in the inline-progression direction by 21270 millipoints. (See position 1479:98)```

В тексте книги
```"zombie", in the philosophical usage of the term, is putatively a being that is exactly like you in every respect—identical behavior, identical speech, identical brain; every atom and quark```

- Символы которые fop не может найти в шрифтах
```[WARN] FOUserAgent - Glyph "?" (0xdbff) not available in font "CharisSIL".```
```[WARN] FOUserAgent - Glyph "?" (0xdc09) not available in font "CharisSIL".```

**Comment by yozhio** [comment]
**Генерация html**
Не все параметры картинок перенесены из оригинальных html-файлов в dbk. Не хватает оформления картинок из стилей: выравнивание, обтекание текстом итп. Соответственно эти параметры не дошли до cгенерированных html-файлов.

**Comment by worldmind** [comment]
На этом пока остановимся, все эти замечания нужно потом в отдельные тикеты внести, но и потом надо будет в Makefile поменять чтобы русскоязычная книга собиралась вместо англоязычной.
